version: '2'
services:
  elasticsearch-ingress1:
    container_name: es-g1
    hostname: es-g1
    restart: always
    build:
      context: elasticsearch/
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es-g1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/es-g1/data:/usr/share/elasticsearch/data
      - ./elasticsearch/backup:/usr/share/elasticsearch/backup
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch-master1:
    container_name: es1
    hostname: es1
    restart: always
    build:
      context: elasticsearch/
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/es1/license:/usr/share/elasticsearch/license:ro
      - ./elasticsearch/es1/data:/usr/share/elasticsearch/data
      - ./elasticsearch/backup:/usr/share/elasticsearch/backup
    networks:
      - esnet

# Second Master Container
  elasticsearch-master2:
    container_name: es2
    hostname: es2
    restart: always
    build:
      context: elasticsearch/
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/es2/data:/usr/share/elasticsearch/data
      - ./elasticsearch/backup:/usr/share/elasticsearch/backup
    networks:
      - esnet

# Thrid Master Container
  elasticsearch-master3:
    container_name: es3
    hostname: es3
    restart: always
    build:
      context: elasticsearch/
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es3/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/es3/data:/usr/share/elasticsearch/data
      - ./elasticsearch/backup:/usr/share/elasticsearch/backup
    networks:
      - esnet

  elasticsearch-data1:
    container_name: es-d1
    hostname: es-d1
    restart: always
    build:
      context: elasticsearch/
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es-d1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/es-d1/data:/usr/share/elasticsearch/data
      - ./elasticsearch/backup:/usr/share/elasticsearch/backup
    networks:
      - esnet

  elasticsearch-data2:
    container_name: es-d2
    hostname: es-d2
    restart: always
    build:
      context: elasticsearch/
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es-d2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/es-d2/data:/usr/share/elasticsearch/data
      - ./elasticsearch/backup:/usr/share/elasticsearch/backup
    networks:
      - esnet

  logstash:
    container_name: logstash
    hostname: logstash
    restart: always
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    networks:
      - esnet
    depends_on:
      - elasticsearch-master1

  kibana:
    container_name: kibana
    hostname: kibana
    restart: always
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch-master1

  nginx:
    container_name: nginx
    hostname: nginx
    restart: always
    build:
      context: nginx/
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./nginx/error/:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - esnet
    depends_on:
      - kibana

  apm-server:
    container_name: apm-server
    hostname: apm-server
    restart: always
    build:
      context: apm-server/
    volumes:
      - ./apm-server/config/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
      - ./apm-server/config/fields.yml:/usr/share/apm-server/fields.yml:ro
      - ./apm-server/data:/usr/share/apm-server/data
    ports:
      - "8200:8200"
    networks:
      - esnet
    depends_on:
      - elasticsearch-master1
      - elasticsearch-ingress1
      - kibana

networks:
  esnet:
